# Labs


In this chapter you will find the lab materials/activities. Slides will be linked in this chapter, but can be found on Moodle. Each lab focuses on supporting you with your qualitative project. As part of this project, you will complete two summative assessments: one as a group (30%) and one as an individual (50%).

The Labs will be on the following topics:

- Week 1: What is qualitative research?
- Week 2: Group work, Developing Research Questions
- Week 3: Ethics
- Week 4: Developing a focus group schedule
- Week 5: Running a focus group
- Week 7: Data processing and reflection
- Week 8: Evaluation in the Introduction and Discussion
- Week 9: Analysis (coding)
- Week 10: Analysis (themes)


## Week 1 Lab 1: What is qualitative research?

 - - - - 

Key resources: 

[Project timeline](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EYepOBxHkIxKuULVqBmvGiMBk7KH4FlUNGMLWlpYNc7d4Q?e=6rgfh2)

 - - - - 

In Lab 1, we will introduce you to qualitative research, and consider the differences between qualitative and quantitative. You will work together in groups to complete two activities. 

### Lab 1 Activity 1: Differences between qualitative and quantitative studies

Look at the table below, then discuss the questions underneath in your groups.


|Quantitative             |Qualitative           |
|-------------------------|----------------------|
|Numbers used as data     |Words (written/spoken) and images used as data.|
|Seeks to identify relationships between variables to explain or predict with the aim of generalising findings to a wider population|Seeks to understand and interpret more local meanings. Recognises data as gathered in a context. *Sometimes* produces knowledge that contributes to more general understandings|
|Generates "shallow" but broad data: not a lot fo complex detail obtained from each participant but lots of participants take part to generate statistical power|Generates narrow but rich data - "thick descriptions" - detailed and complex accounts from each participant, not many participants|
|Seeks consensus, norms or general patterns, often aims to reduce diversity of responses to an average response|Tends to seek patterns but accommodates and explores difference and divergence within the data|
|Tends to be theory-testing and deductive|Tends to be theory generating and *inductive* (working up from the data)|
|Values detachment and impartiality (objectivity)|Values personal involvement and partiality (subjectivity, reflexivity)|
|Has a fixed method (harder to change focus when data collection has begun)|Method is less fixed (can accommodate a shift in focus in the same study)|
|Can be completed quickly|Tends to take longer to complete because it is interpretative and there is no formula|


  + What might a 'typical' *quantitative* study look like? What kind of data might be collected? What would be the aim of the study? What might your sample look like?
  + What might a 'typical' *qualitative* study look like? What kind of data might be collected? What would be the aim of the study? What might your sample look like?
  + What type of research question might be best answered with a *quantitative* design? 
  + What type of research question might be best answered with a *qualitative* design? 


### Lab 1 Activity 2: Qualitative or quantitative?

Choose whether a quantitative or qualitative design is most appropriate for each of the following studies. Why did you choose each option?

  1. Angela is conducting a study exploring the experience of people currently experience mental ill health. She is interested in a) better understanding what people with mental ill health experience day-to-day, and b) exploring the support mechanisms that are in place.
  2. Ali is conducting a study where he is measuring whether the amount of sleep that children get is related to their cognitive performance in class. He asks the children to wear a sleep tracker to bed, so he can see when they are sleeping and when they are awake.
  3. Sally is conducting a study where she is interested in the effects of violence on TV on children.
  4. Charlie is conducting a study where they want to better understand motivations for smoking among teenagers.
  5. Elaine is conducting a study exploring whether the amount of studying done in preparation for an exam predicts exam performance.


## Week 2 Lab 2: Groupwork and RQs

 - - - - 

Key resources: 

[Topic Guide](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-preparation-group.html#topic-guide)

[Group Agreement Info](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-preparation-group.html#group-agreement-and-task-allocation)

[Group Agreement and task allocation template](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EX0j7-IboldEnapucgQ7h-YBgvV1_YeuUcNhWi9z_996oQ?e=BkLLbx)


 - - - - 

In Lab 2, you will form into the groups that you will  be in for the rest of the semester. You will be able to find your group in the spreadsheet at the bottom of the [Week 2 Moodle](https://moodle.gla.ac.uk/course/view.php?id=38155&section=3) (please note the spreadsheet will only become available once it has been released at the start of Week 2). In these groups, you will a) design, run and transcribe a focus group with a group in your lab as your participants, b) participate in another group's focus group, and c) write a qualitative group proposal. 

In today's lab, there will be some time spent getting to know each other, then we will ask you to develop a group agreement (see below). You should also discuss the [different topics](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-preparation-group.html#topic-guide) that you can choose for your project, seeing whether any stand out as preferred options among the group.

### Lab 2 Activity 1: Group Agreements and Task Allocation

We appreciate that group work can be challenging and we want to support you to have an enjoyable and educational group work experience. To that end, we would like each group to create a group agreement that all members sign. The purpose of this is for the group to come together and establish common ground and rules that each of the group members is committed to. 

After you have all introduced yourselves, download the [group agreement template](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EX0j7-IboldEnapucgQ7h-YBgvV1_YeuUcNhWi9z_996oQ?e=BkLLbx). Then look at the list of potential items to include. These are provided within the template document itself, as well as in **Chapter 2.2.1.** As a group, discuss which items you want to include in addition to the standard ones provided, and if there are any you would like to edit or add outside of this list. 

After this, you should allocate tasks for the **group proposal** among the members of the group. A starter list of tasks is provided in the template as well as in **Chapter 2.2.2**. The task allocation must be uploaded in the same document as the signed group agreement.

Work on a collaborative document on OneDrive to create your group work agreement and allocation of tasks for the group proposal. Once the group is happy with their agreement, *each group member* should sign it and submit it to Moodle individually (Formative Assessment Section). You can either all sign the same document and upload a copy each, or you can sign separately and upload the copy that only you have signed. Each person should submit their signed group agreement and task allocation before their lab in Week 3. 

Once the deadline has passed, we will be in touch with any groups where any members have not uploaded a group agreement and task allocation for the group proposal. 

### Lab 2 Activity 2: Research Questions

In your groups, have a look at the Topic Guide. There are three topics to choose from: Green Spaces, Belonging and Mental Health. 

Have a look over the topics - are there any that your group are particularly drawn towards at this stage? You might know immediately what you'd like to focus on, or might need to discuss all of them in your group. 

Once you've chosen a topic (you might not manage this in the lab, which is fine!), have a think about possible research questions. You will need to have a finalised RQ for your group proposal, which is submitted in Week 5. 

## Week 3 Lab 3: Ethics

 - - - - 

Key resources: 

 - - - - 

In Lab 3, we will cover ethics and you will complete two activities within your groups. 

### Information required for the lab activities

**Research Question (this is also relevant for our FG questions)**

*This might look like:* In qualitative research, we often ask about someone’s lived
experience, or their motivations, or a belief they have. This is quite different to
quantitative research.

*Why might this be an issue:* Qualitative research tends to be on topics where we ask
people to be vulnerable and open themselves up to us as researchers. If we don't frame
this correctly, our interview schedule might contain questions that are inappropriate.


**Data Collection**

*This might look like:* Data collection is much less likely to be anonymous, as typically in-
person or online focus groups or interviews are held. Samples are small, and
participants may already be known to the researcher.

*Why might this be an issue:* There are possible issues of confidentiality, anonymity
(these will be discussed further down) and bias. Our preconceptions might affect the
way we frame the questions, how we interact with participants in the focus group, and
how we interpret the data.


**Recording a focus group or interview**

*This might look like:* The majority of the time, focus groups and interviews are recorded
(either audio + video or audio only). This means that the 'raw' data - as it were - is
identifiable. In contrast, data for quant studies are often collected anonymously.

*Why might this be an issue:* Data should always be kept safe and secure. However, with
qualitative data, there is a real risk that individual people could be identified from a
recording of them. This  means that dealing with the recordings in a safe and secure
way are of utmost importance, and that participants cannot be identified from
transcripts.


**Anonymity**

*This might look like:* In quantitative research, we tend to report summary statistics from
groups, and therefore it’d be quite unusual to be able to identify a single participant
from the data. With qualitative, it’s a bit different. We collect people’s words and
experiences.

*Why might this be an issue:* It is easier to identify someone from the words they use,
and the situations and circumstances they describe.


**Confidentiality**

*This might look like:* In a focus group or interview, people might be very open with us,
and tell us things about their life, and the lives of others.

*Why might this be an issue:* We have a duty of care to keep anything that comes out in a
focus group/interview confidential (unless they disclose a crime or someone is judged
to be at risk). It’s also vital that the rest of the focus group members keep the
information confidential too.


### Lab 3 Activity 1: Mitatigation of the issues

Consider the issues in the section above. In your groups, discuss each one in turn, thinking about the various steps that could be taken to reduce or remove these issues.

The issues that should be discussed are:

- Research Question
- Data Collection
- Recording a focus group or interview
- Anonymity
- Confidentiality


### Lab 3 Activity 2: Fictional focus group example

Angela and John have run a focus group study to explore the experiences of UK university staff members during the pandemic. Below you will find their focus group schedule (the questions that they asked in the focus group), some correspondence they had about the study, and an excerpt of their data for the final write-up they are about to submit to a journal. 

In your groups, try to identify what ethical issues there are, and how they could have been mitigated.


```{block, type="info"}
**Focus group schedule**

1. What has been your experience with teaching during the pandemic?
2. How has this affected your personal life? What impact has your increased workload had on that? 
3. Can you describe some of the negative effects that this has had on your mental health? 
    Prompt: What has been the worst thing about the pandemic for you?
4. How has your employer supported you during the pandemic? 
5. How has your student contact differed from previous years? 

**Correspondence between the authors**

*Email 1:* 

“Hi Angela,

Please see attached a Google Drive link to the raw data with focus group number 3. I’m just working on the anonymisation of FG4 on the library computers and will send it to you asap.

Cheers,

J”

*Email 2:*

“Hi,

Thanks for the update! Actually my dissertation student is very interested in the topic so I thought they would help with the data analysis – can you share the raw data folder with 12345@student.gla.ac.uk also?

-Angela”


**Data Excerpt**

Participant 1: “For me, as I’m the course lead for first-year philosophy, the workload was
just simply too much to handle at times and I felt so alone.”

Participant 2: “Yeah, I agree, umm, it was really hard to just keep going with extra hours
and that feeling of isolation”

Moderator: “What about you, Participant 3, how was your mental health affected
negatively?”
```

## Week 4 Lab 4: Developing Focus Group questions

 - - - - 

Key resources:

[Bank of questions for the focus groups](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-data-collection-and-processing-group.html#collecting-data-questions)

 - - - - 

In Lab 4, we will work on developing questions for your focus group. We have made a [bank of questions](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-data-collection-and-processing-group.html#collecting-data-questions) available to you. Please select any questions that you would like to use and then adapt them to suit your research question. 

If you have developed a research question that means you need different focus group questions to those in the question bank,then you may need to make up some new questions to go into your focus group schedule. 

If you develop new questions that have not been adapted from the bank of questions provided, please ensure you do the following:

1. Questions must be developed using the guidance provided to you in this lab
2. You **must** attend your tutor's office hours and ask for feedback on your questions. 

If, however, you only use questions from the bank that is supplied or make minor tweaks, you are not *required* to formally discuss these with your tutor (although you are welcome to do so if you have specific questions that you want to ask). You might, for example, want to check the order that you present the questions in. 

### Lab 4 Activity 1: Research Questions

Please have your Research Question ready for your tutor, and discuss it with them as they come round the groups. Do you have any other questions about the group proposal that you want to ask? Please work on the other two activities until your tutor makes it to your group.

### Lab 4 Activity 2: Appropriateness of questions

Look at the following focus group questions. For each, decide whether a) they are appropriate and b) whether they should be adapted or not, If you think they should be, how would you change them? 


```{block, type="info"}
*Research Question: How does students' sense of belonging relate to participation in team sport?*

1. How many hours of group sport do you participate in each week?
2. What does being a part of a team mean to you?
3. What does belonging mean to you? 
4. How has your sense of belonging improved since joining your sports group?
5. I'm going to go round the group one at a time. I need each person to tell me about a time where they've felt that they haven't belonged to their team, and how that impacted on them personally? 
6. Please tell me, on a scale of 1-5 (with 1 being not at all and 5 being hugely) how much you feel like you belong to your sports team?
7. Do you like being a part of a sports team?
```



### Lab 4 Activity 3: Rewording questions

Have a look at these poorly written fictional focus group questions. The research question is there to help you (you do not need to re-word this). 

```{block, type="info"}
*Research question: Exploring international students' experiences of their sense of belonging and homesickness*

1. Have you ever felt homesick while studying abroad?
2. How has this negatively affected you?
3. How often do you feel like you don't belong?

```

- Try to re-write these questions to improve them, thinking about the clarity and the quality of data they would give you
- Write your own question to add to the revised questions above, thinking about the guidance you’ve been given about developing good questions


## Week 5 Lab 5: Running a Focus Group

 - - - - 

Key resources:

[Checklist for focus group](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EaGHiB_KPM1Jgn22rGnqVJ8BeLmxD2D2dDtiEBC0bE0FZQ?e=nRvCZQ) 

[Task Allocation for focus group](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-preparation-group.html#focus-group-task-allocation-see-lab-5)

[Information Sheet template](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EXjnUsZm6aFGhI5mX0E3tqoB8aI3vJRZCP7h4eAAfTqi7g?e=wJVIEz)

[Consent Form template](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ETFRTON4cnROjUYI6WGc2wIBzjmRkzk8kpDdH79asr27BQ?e=TBJ4S7)


 - - - - 

In this week's lab, we will cover some key things that you will need to know in order to run a focus group. We also have some activities for you to do in groups. 

### Lab 5 Activity 1: Allocation of tasks


Look at the list of [focus group tasks](https://wtoivo.github.io/RM2-F2F-quali-book/qualitative-project-preparation-group.html#focus-group-task-allocation-see-lab-5) in the Group project: Preparation chapter of this book.

Allocate tasks between your group members (write this down and make sure everybody has a copy of it). If you are missing group members, make sure to catch up with them and discuss task allocation. 

### Lab 5 Activity 2: How would you manage these situations?

In your groups, discuss the following scenarios. What might you do if these happen when you run your focus groups? What might you try to help the situation?  

```{block, type="info"}
1. Nobody answers the questions you have asked
2. The conversation goes completely off-topic
3. One participant dominates the conversation
4. One participant is seemingly uncomfortable and doesn't say anything
5. Participants don't seem comfortable/confident answering questions in English
```

Note down some suggestions among the group about how you might manage these situations and we will discuss as a class. 


## Week 7 Lab 6: Data processing and reflection

 - - - - 

Key resources:

[Reflection document](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ES-Vc-s5kxZGo8wqcvvfmawBjrTG_q6WpNtTT18StzwS8w?e=aY8Pmx)

 - - - - 

### Lab 6 Activity 1: Anonymise the transcript

Take a look at the short excerpt below. In your group, try to anonymise it, thinking about whether you would choose to redact or replace the information.  

```{block, type="info"}
**Transcript:**

Jane:...I grew up in Brighton and you see men holding hands all the time in Brighton, and Tim came out when I was about 12 or 13 (pause) I think he was 16 or maybe 15, he was definitely still at Michael Hall because I used to get teased about being gay myself...

Interviewer: And, when did you come out?

Jane: I came out in the first year of university so I must have been 19 or 20, I had a gap year before going to Durham...my mum freaked a bit, she was totally okay, but I think even for her – someone who lives in Brighton and writes for the Guardian – two gay kids was a bit much... my Aunty Julie, my mum’s sister, was absolutely wonderful though, and she’s a lesbian...
```

Did you agree on all the points? If not, why not? Remember that there is no one 'correct' answer; it's not unusual to have different opinions about how you should approach it!

### Lab 6 Activity 2: Reflection on RM1 

Feedback is most useful when it is reflected on and incorporated into subsequent assessments. For this reason, we ask you to complete an activity where you reflect on the feedback you received in RM1, thinking about what you want to focus on for your RM2 report. 

- Complete [this document](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ES-Vc-s5kxZGo8wqcvvfmawBjrTG_q6WpNtTT18StzwS8w?e=aY8Pmx), reflecting on the RM1 feedback you received, and considering what you might focus on improving for your RM2 report.
- You will need your RM1 registered report feedback (both Stage 1 and Stage 2) and the Qualitative report AIS to complete this activity


## Week 8 Lab 7: Evaluation in the Introduction and Discussion


We often ask for students to demonstrate *evaluation* in their writing, i.e. going beyond paraphrasing and descriptive writing. Essentially, we are looking for you to develop critical, evidence-based arguments that demonstrate your thinking. 

In today's lab, we are going to focus on how you might incorporate evaluation into your introduction and discussion. This will not only support you for the RM2 report, but also any other submissions you have (including your dissertation). 

### Lab 7: Activity 1: Evaluation in Introductions

The purpose of your introduction is to provide a rationale for your study and answer the WHY question; why is your study worth doing? You want to sell your idea to the reader, using existing literature to show how you are building on the evidence that is there.

In Activity 1, read the following extracts from an introduction section. As a group, identify *two* aspects of evaluation that could be improved for this study.  

```{block, type="info"}
**Extract 1**
A study by Lane and Karin (2011) looked at zombie apocalypse survival confidence levels in undergraduate students. The sample consisted of 25 participants (20 male and 5 female), recruited through convenience sampling. The study employed involved a survey comprising Likert-scale questions designed to measure participants' self-assessed confidence in various survival skills. Additionally, participants were asked about their exposure to zombie-related media. The data were subjected to t-tests and regression analyses, and the authors’ found that the biggest predictor of zombie apocalypse confidence was exposure to zombie-themed video games.

**Extract 2**
It should be noted that the majority of studies on zombie apocalypse survival confidence have looked at samples that consist of mostly men (Lane & Karin, 2011 but see also Grimes & Dixon, 2019), and that previous samples have been small.

**Extract 3**
To date, there has been only one qualitative study on the topic – Seok (2013) collected data through semi-structured interviews, which were analysed using thematic analysis and two themes, “Survival mode” and “Confidence through skills” were identified. This study looked at undergraduate students; there is no previous literature on postgraduate students’ perceptions of their apocalyptic confidence. Therefore, this qualitative study investigates the perceived confidence of postgraduate students in their abilities to survive a zombie apocalypse.
```

### Lab 7 Activity 2: Evaluation in Discussions

The purpose of your discussion is to summarise your results, contextualising them and situating them within the broader research context.  As part of this process, it is important to consider the implications of your work, as well as the limitations and possible future directions. Discussions should be rooted in the evidence base, rather than based on personal opinion.

In Activity 2, read the following extracts from a discussion section. As a group, identify *two* aspects of evaluation that could be improved for this study. 


```{block, type="info"}
**Extract 1**
In this study, our investigation into the realm of confidence in preparing for the zombie apocalypse has revealed nuanced insights into individuals' perceptions of their readiness for this so-far-unrealised scenario. Theme 1 was perceived media influence of feelings of preparedness. Here, we found that participants were more likely to feel prepared for the apocalypse when they watched zombie TV shows, which is in line with Lincoln and Reedus (2014). In Theme 2, we found that confidence was improved through perceived cooperation. This does not align with the most recent evidence, namely Morgan et al. (2023). These findings contribute to our understanding of how individuals navigate the complex interplay between personal beliefs, social interactions, and cultural representations when assessing their preparedness for extreme and unlikely events.

**Extract 2**
There were a number of limitations in this study. Firstly, it is important to note that we were unable to generalise as there were only four participants in the study. Secondly, we are currently unable to tell whether confidence in zombie apocalypse survival translates to real-world skills. Finally, a limitation is that the questions did not consider how postgraduates might reduce their vulnerability to zombie attacks.

**Extract 3**
This study offers insights into broader psychological phenomena and practical interventions. Governments around the world should take these findings and incorporate them into their disaster relief programs. This will enable policymakers and educators to further enhance individuals' capacity to critically evaluate their preparedness, bridging the gap between perceived and actual abilities. Moreover, this research illuminates the ways in which fictional contexts can impact real-world perceptions, shedding light on cognitive biases and media's potential to shape individuals' self-assessment (Masterson, 2020). As the world faces increasingly diverse and unpredictable challenges, understanding how individuals approach threats from the zombie apocalypse helps foster a holistic approach to readiness in an ever-changing landscape.
```


## Week 9 Lab 8: Analysis (coding)

 - - - - 

Key resources:

[Trancript to code](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ETYhcd1SnIRCmeM-gBPyGAEBVyitlNYkOMhPVrih1m8N4w?e=HHZ0LQ)

 - - - -

In this week's lab, we are going to focus on coding (i.e. step 2 of Thematic Analysis). We have one activity to support you in the coding stage of your data analysis. 


### Lab 8 Activity 1: Coding

- Read over [this transcript](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/ETYhcd1SnIRCmeM-gBPyGAEBVyitlNYkOMhPVrih1m8N4w?e=HHZ0LQ), becoming familiar with it. Take some initial notes.
- In your groups, code the data together. Note down anything that seems important and that you think encapsulates the data. Do you all agree on the codes or are there differences of opinion (remember it's okay if you don't all agree!)?
- Post the codes that your group has chosen [on mentimeter](https://www.menti.com/altq7f73uqs7)

#### Transcript

```{block, type="info"}
Extract from E_NM4 Interview [LGBT staff networks on UK Data Service](https://reshare.ukdataservice.ac.uk/855322/)  

RESEARCHER: 
So, how do you, how do you influence the organisation or how do you try to influence the organisation? 

CHARLES: 
Erm, the best person to go to in this organisation is, Lillian.  

RESEARCHER: 
Why's that? 

CHARLES: 
Because, erm, she'll give you a cut and dry answer, a yes or a no, erm, which is great, 'cause that's what you want, you don't want - I don't want to go to someone that, if I go to Leo with it, generally it's, what's it gonna cost me? So, we have a budget of the group, but if it's above the budget, then it's, what's it gonna cost, and then it's always, there's to-ing and fro-ing. Erm, if you go to the levels of management within the Trust, it always gets passed to other people, erm, one example of this is when we got the rainbow lanyard, erm, I, I said to Leo I wanted to get some, erm, we'd got them for getting in the Stonewall Top [ranking] the first year, so Leo agreed that he'd get them. He bought them and then, they came into the organisation and then, er, he said, oh, I've been speaking - he'd spoken to someone and they said, oh, you're gonna have to get approval for them to go out and be used, so I think we were gonna put them out for LGBT History Month initially, but then they just sort of stayed. Leo had gone to HR and HR had said, oh, it's the uniform policy, we don't own that, you'll have to go to ops, operations, so Leo went to operations and they said, oh, we don't own that policy, it'll be HR, you'll have to go to them, so he went back to HR and HR said, well, we're not comfortable saying it 'cause it'll have an impact on ops and it'll have an impact on this, so you'll have to go to - and it just went round and round and round and for like, ten days, Leo was like, I don't know where to go with it, I really don't know what we do, no-one will take ownership. So, I, I picked one of the lanyards up, walked into Lillian's office and said, do you like this, and she said, oh yeah, it's great, can I have one, and I was like, yep, there we go. I was like, the problem is, we don't know who owns the policy, who can we - and immediately she went, no, this is, this is what it's for, this is what it is, put them out, and I think, you know, sometimes you just need someone who's gonna make them decisions and be like, yes actually, we'll support it.  


RESEARCHER: 
Yeah, yeah, no, I can see that, it's kind of a straight answer and, you know, not being sent, you know, around into a circle. So, do you think, you know, when you're thinking about what the network is doing now, do you think the network should be doing something else? 


CHARLES: 
Erm, I don't think we have the capacity to do any more. I think, erm, it'd be great if we had enough people that, someone sat on all of the meetings and all of the groups within the Trust, it had a, a staff network member, erm, I've found that as the chair of the group, I get invited to a lot of these groups now, erm, and I do try and attend as many as I can, so I'm now on a health and wellbeing group and I'm on, erm, there's another one I'm on, erm, but there's other that like, the vehicle working group. I'd like to have someone sat on there so actually, we could influence it, actually could we have an LGBT sticker or can we have - do you know what I mean? Just, and it might be that they have no input for long periods, but there's certain points where there might be that point where they can go, actually, that isn't suitable for LGBT staff. Erm, the - but I'd need more people to step up, I'd need more support, erm, I know with, Camila, that's just joined the group, erm, she's really keen and she's really showing promise now, which is great and sort of, can start seeing if she'll attend some of these meetings. But I'm aware that her manager at the minute is really busy, and she's getting lots of work and I'm not sure what the release is gonna be like for her to go and do this stuff, 'cause that's the other issue.
```



## Week 10 Lab 9: Analysis (themes)

 - - - - 

Key resources:

[Zombie Apocalypse transcript](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EdAZ7naOqiFNtrfDFX-QanABpgJz6sJo9493G68rXKyCIw?e=yBhaqi)

 - - - - 

In today's lab (which is our last one in RM2), we have two activities to support you with developing themes using Thematic analysis. If there is time, you will also have the opportunity to get started on your analysis in Activity 3.

### Lab 9 Activity 1: Theme Names

Naming and refining your themes (stage 5) is an important step in communicating your analysis to your reader. 

Below, we have some theme names that are based on a [Zombie Apocalypse transcript](https://gla-my.sharepoint.com/:w:/g/personal/ashley_robertson_glasgow_ac_uk/EdAZ7naOqiFNtrfDFX-QanABpgJz6sJo9493G68rXKyCIw?e=yBhaqi). 

As a group, discuss these theme names. Do you think they are good/poor? Are you able to tell what type of data might be captured under each theme?

- Theme 1: Apocalypse confidence
- Theme 2: Survival
- Theme 3: The importance of media
- Theme 4: Zombie preparedness planning 
  - Subtheme 1: Negative aspects of planning
  - Subtheme 2: Positive aspects of planning
  
### Lab 9 Activity 2: Going deeper in your analysis

One of the characteristics of a strong analysis section is that the writer demonstrates an ability to go beyond paraphrasing/summarising. This activity is designed to help you understand what might be involved in doing so. 

Read the following two extracts from an Analysis section and discuss these questions:

1. Which of the two examples is better? Why?
2. What have the authors done that makes the analysis better?

```{block, type="info"}
**Extract 1 - from a study about the impact of the COVID pandemic**

Sarah spoke of using her leisure time to plan and fantasise about her wedding: 

*“it’s enough of a fantasy… it’s meant to be stressful, but it’s really just been fun. It’s like such a nice break from this humdrum life we’re living in right now” (Sarah: lines 459-461).*

Organising a significant life event seems to be viewed as granting Sarah an escape from her current monotony. While she refers to it as a “fantasy”, potentially given uncertainty of the pandemic’s progression, she appears to perceive this as constructive and realistic for her future self. Alternately, Mandy’s leisure activity involved impossible daydreams:

*“I started daydreaming more ridiculous stuff... I know it’s never going to come true ‘cause it’s not real, but it still entertains me” (Mandy: lines 443-444)*

While Mandy seems to be under no illusion that her daydreams are feasible, daydreaming impossible scenarios appears to provide more of a release than realistic situations that are subject to ever changing government regulations (e.g. travel bans) that may fall through.
```


```{block, type="info"}
**Extract 2 - from a study about social media use during the pandemic**

Some participants said it was difficult to fall asleep at night, including those who knew they should fall asleep but could not (*"if I can't stay up and can't sleep "- Sarah*), or participants subjectively thought that they did not need sleep or did not want to fall asleep (*"I am not really able to sleep at night, or like, sleep isn't really needed."* -Andrew)

Participants said that they used social media but that it was only positive at certain points:

*I feel like TikTok was fun in the first lockdown during the summer,'cause of all this summer content I guess, but after that it really went downhill. I don't know like, OK personally I deleted all my apps about three weeks ago* (John)

John tells us here that he deleted all his apps, because they all went ‘downhill’. Tik Tok was helpful during the first lockdown, but not after it.
```


### Lab 9 Activity 3: Reflexivity

This activity is designed to help you with the reflexivity section in your report.Individually, take notes on the following, using it to help you when you come to write this section:
 

- Are you an insider or outsider researcher (i.e. do you belong to the group you are researching or not?
- What implications might this have for how you ran your study and how you analysed it?
- What preconceptions or expectations did you have about the topic before you ran your focus group?
- Did what your participants say agree or disagree? What effect did this have on the way you approached a) data collection or b) data analysis? 