# Group proposal

**FOR DISCUSSION: Should the topic guide be in here, in the qualitative report section, or have it's own section?**

## Topic Guide

As part of your qualitative project, you will be expected to write a review of the literature as part of your Introduction section. It is important that the Introduction has a clear rationale which supports your chosen research question.  

What follows here is an outline of various topics you should consider when you develop your research question, and which form the starting point for you project.  

One of the aims of qualitative research is to be critical of some of the assumptions made by mainstream quantitative studies and to highlight their limitations. In highlighting limitations, you should aim to develop research questions that address weaknesses identified and provide a rationale for using a focus group methodology. 

You should use this topic guide to help you plan your study, and support you with your research questions and rationale assignment. However, you are in no way expected to read everything in the reference section (or even within each topic). These references are provided purely to give you a starting point, and you are encouraged to go beyond the scope of what is provided here.

After the four topics have been presented, we will provide some information about your rationale, and also some key steps for moving forward.

**Four topics of research:** 

1. Green spaces (**Check wording and get blurb from Level 3**)
2. Campus climate: perceptions and experiences of inclusion in higher education
3. Students and mental health
4. Belonging at University

### Topic 1: Green Spaces

Add in 

#### Green Spaces: Potential project topics

Add in

### Topic 2: Campus Climate - perceptions and experiences of inclusion in Higher Education

Campus climate is broad term which refers to the experiences of inclusivity, accessibility, and respect for the needs of diverse individuals and groups on-campus (see Hart & Fellabaum, 2008; Rankin et al., 2019). This project focuses on the perceptions and experiences of inclusion and campus climate in higher education, with a focus on the inclusivity of LGBTQ+ people and people of colour (POC). Focus group participants will be allocated to each group to ensure all students in the class can participate in the research. This means that your participants will be diverse and may/may not identify as LGBT+ or POC students. With this in mind, research questions are designed to be inclusive and ethical, encouraging all students to participate in an open discussion. 

**LGBTQ+ students**

There has been an increase in the number of university applicants who disclose an LGBTQ+ identity in their UCAS application, with 7.2% of the total UK domiciled applicants in 2020 (UCAS, 2021a). Data from UCAS (2021a), suggests that positive campus climate experiences at school or or college are related to students being able to express their LGBTQ+ identities openly, while negative experiences are related to harassment based on identity and a lack of LGBTQ+ representation in the school/ college educational curriculum. Within the university curriculum, how LGBTQ+ friendly an academic subject area is perceived depends on how inclusive the subject is of LGBTQ+ identities (Forbes (2020). Subject areas are perceived to be more LGBTQ+ friendly if they provided a platform for discussion of LGBTQ+ issues (e.g. in humanities and social sciences), compared to subjects which did not easily lend themselves towards such discussion (e.g. STEM). In Forbes (2020) study, LGBTQ+ students also reported that they would be more likely to seek support from faculty staff in subjects perceived to be more LGBTQ+ friendly, than those in other subjects due to the teaching staff’s experience in discussing LGBTQ+ issues.  

To enhance the experience of LGBTQ+ students’ experience in higher education, and to increase LGBTQ+ representation across the curriculum, higher education institutions often provide support, resources, and networks as part of their inclusivity and diversity strategy (e.g. Advance HE, n.d. -a; University of Glasgow, n.d. -a; University of Glasgow, n.d. -b). However, discipline-related differences in LGBTQ+ inclusivity have been reported in the workplace. For example, LGBTQ+ people in STEM careers report fewer career opportunities and feelings of being devalued and socially excluded, which has led to greater mental health difficulties and a higher likelihood of leaving STEM, compared to their non-LGBTQ+ counterparts (Cech & Waidzunas, 2021). Furthermore, LGBTQ+ staff in STEM university departments were more likely to experience harassment and social exclusion than those in non-STEM departments (Bilimoria & Stewart, 2009; Partridge et al ., 2014). 

**Students of colour**

The number of POC entering higher education is increasing (UCAS, 2021b); however, in 2019, 13.2% fewer POC students were awarded a first or upper second class degree compared to white students (Universities UK, 2019). The Black Lives Matter movement and 2020 racial protests across the world have brought attention to the issues of systemic racism, prompting institutions to act in dismantling systemic racism, particularly within higher education (e.g. Advance HE, n.d. -b; University of Glasgow, n.d. -c). Given that there is an underrepresentation of people of colour (POC) in university curricula in general, and that much of psychological research is based on samples from Western, educated, industrialised, rich and democratic countries (Henrich et al. 2010), there have been calls to diversify the university curriculum to better represent the experience and knowledge of POC (e.g. on course reading lists, in research sampling). Furthermore, there have been calls to decolonise the psychological curriculum (De Oliveira, 2020), with the aim of dismantling systemic racism by examining biases, assumptions, and inaccuracies in the representation of race in the curriculum (Gillborn et al., 2021).  

Gillborn et al (2021) found that the underrepresentation of POC in the university curriculum was recognisable to POC students, and that this extended beyond curriculum content to the representation of POC in teaching staff and the naming of campus buildings, but that they felt powerless to effect any change to the curriculum. POC students have also reported a lack of relatedness, competence and autonomy in their academic life, and that teaching staff can play a key role in removing these barriers (Bunce et al., 2021). Similarly, Varney et al. (2020) found that feedback from peers and teaching staff could either foster or hinder the sense of emotional safety that would allow POC students to express their identity; however, they also report that POC students felt pressure to represent their communities and were fearful of perpetuating stereotypes and being target because of their self-disclosure. 

#### Campus climate: Potential project topics

- What are students' perceptions/experiences of campus climate for LGBTQ+, POC and/or other minority identities or groups in HE? 
- What are students' views on how universities can better support LGBT+ and students of colour? How accessible is information on university policy and support for these minority groups? 
- How can we increase awareness of the issues faced by LGBTQ+ and POC students? 
- How does representation of LGBTQ+ and POC groups within a subject discipline influence the experiences and perceptions of all students? 
- What is the impact of visibility of LGBTQ +/POC staff on students' experiences and perceptions?  

These are example questions. You are encouraged to develop these ideas or come up with new questions based on your reading.  

### Topic 3: Students and mental health

There has been increasing concern about the mental health of students at university. In a survey of over 2,000 students, suicide ideation was reported by 2%.  Anxiety and depression symptoms were also commonly reported (Eisenberg et al., 2007). Another study conducted over two time points found that mental health problems are persistent and that many people do not seek the help they need (Zivin et al., 2009). 

Interestingly, it has been shown that sleep disturbances in students, when treated, can also improve mental health status (Freeman et al., 2015), suggesting an intimate link between sleep and mental health. Guidelines have been published by the American Academy of Sleep Medicine as to how much sleep is recommended across different age groups. For teenagers aged 13-18 , 8-10 hours are recommended, for adults (aged 18-60), 7 hours or more on a regular basis is recommended for optimal mental and physical health (Badr et al., 2015). Indeed, getting an adequate amount of sleep is associated with lower anxiety, tension, depression and higher satisfaction with life (Pilcher & Walters, 1997). The topic of student’s mental health has received media attention recently with articles suggesting that there is a “mental health crisis” (Thomas, 2018).   

**Students and seeking support**

Universities provide support for students, and this support maybe come in many forms, from free counselling services to well-being advisors (Raunic & Xenos, 2008).  

In one study, it was reported that only 3% of students used their university counselling service, and only 5% of those who were characterised as vulnerable based on questionnaire scores, used the services (Cooke et al., 2006). This suggests that the majority of students did not make use of services available. 

There are many reasons why students may not choose to seek help, including being unaware of services, low socio-economic status, being from an Asian background, embarrassment about having to seek help and scepticism about the services (Eisenberg et al., 2007; Gulliver et al., 2010). 

Another issue around seeking support is that many who do chose to get help, have to wait long periods for appointments (Mowbray et al., 2006). In a recent article reported in the Independent, a waiting time of 4 months was cited for some universities. These delays to support, can lead to emergence of mental health crises situations. Unfortunately, in this the University of Glasgow had one of the longest wait times for counselling (Buchan, 2018).  

#### Students and mental health: Potential project topics

- What are student perceptions of the mental health services provided by Universities? 
- What are student’s views on how universities can support students and their mental health needs? 

These are just two example questions. You are encouraged to develop these ideas or come up with new questions based on your reading.  


### Topic 4: Belonging at University

There is extensive evidence that feeling a sense of belonging (also sometimes referred to as identifying with a group) is considered to be a basic psychological need (Baumeister & Leary, 1995). Feeling like we belong can foster a sense of personal control (Greenaway et al, 2015), increase meaning and purpose in life (Haslam et al., 2018) protect from existential anxiety (Sani, Herrera & Bowe, 2009), and promote reciprocal support (Levine, Prosser, Evans, & Reicher, 2005).  

Furthermore, research has found a robust link between feeling like you belong to a range of different social groups (including family, University, workplace, and friend groups) and positive psychological outcomes. These outcomes include a degree of protection from depression (Cruwys et al., 2014; Sani et al. 2012), anxiety (Sani et al., 2012; Wakefield et al., 2013), post-traumatic stress (Swartzman et al., 2016), paranoia (Sani et al.,, 2017; Greenaway et al., 2018), and cognitive decline (Haslam et al., 2010).  

Thinking specifically about University, having a sense of belonging is associated with academic success and motivation (Freeman et al., 2007). There is also evidence that it is related to students’ wellbeing, with higher levels of postive emotions, self-worth and social acceptance being linked with feelings of belonging to University (Pittman and Richmond, 2007; Wilson et al., 2015). Students who do not feel like they connect with their University may be more likely to disengage, increasing the likelihood of considering leaving university without completing (Pedler et al., 2022).  

Given these findings, it is important to understand what can help facilitate a sense of belonging at University, and what barriers might be in place to reduce the likelihood of feeling like you belong.  

**Facilitating a sense of belonging for students**

There has been a recent focus on how Universities can develop a sense of belonging for their students, e.g, Samura (2022) published an article in The Conversation discussing how we can meaningfully think about belonging at University. WONKHE (an organisation related to debate in Higher Education) and Pearson (an academic publisher) published a (non-peer-reviewed) report exploring ways in which institutions can help students develop a sense of belonging. They found that there were four key areas that were important: connection (e.g. developing friendships and peer connections), inclusion (e.g. diverse, inclusive content), support (e.g. ability to access appropriate support at the point of needing it) and autonomy (e.g. being able to contribute to the wider university experience) (Blake et al., 2022).  

Pedler et al. (2022) found that there are positive correlations between belonging, motivation and enjoyment at University. It also seems to be the case that a sense of belonging is related to specific actions/behaviours that support achievement in students (Gillen-O'Neel, 2021). Many of the studies in this area have looked at these through a quantitative lens, with fewer delving into why these relationships might occur, or why they might be important to students.  

#### Belonging at University: potential project questions

- What can Universities do to help facilitate a sense of belonging for their postgraduate students? 
- What do students perceive as barriers to a feeling of belonging at University? 
- What can postgraduate Psychology Conversion course students do to facilitate a sense of belonging to their University/programme? 

These are just a few example questions. You are encouraged to develop these ideas or come up with new ideas based on your reading.  


### Rationale for using qualitative methodologies

In research methodology “fitting the approach to the research purposes is the critical issue” (Rossi, Lipsey, & Freeman, 2003), therefore all decisions about methodology have to be made after careful consideration about their fitness for purpose. Since qualitative approaches to research design are suited to uncovering new ideas and exploring areas that have not been investigated before (Marshall & Rossman, 2014) your projects will use qualitative methods. 

The main purpose of a focus group is to draw upon the range of respondents’ attitudes and feelings; this could not be done using other methods such as interviews or observations. Compared to individual interviews, which aim to obtain individual attitudes and feelings, focus groups can be used to obtain a group consensus. More data can be collected in a shorter period of time.

When using qualitative approaches their emphasis is on describing a meaningful social world (Silverman, 2015). Quantitative and qualitative approaches produce different, but not incompatible data. Therefore, using qualitative methods does not detract from what already exists within the quantitative literature. 

Indeed, both qualitative and quantitative approaches can produce different data, which together explores the phenomenon. Let's think about it using a different example to those in the topics above. For example, past research in the area of poor quality sleep suggests that whie sleep quality is accepted as a clinical construct, it represents a complex phenomenon that is difficult to measure and define. It could be argued that “sleep quality” can be measured could contain quantitative aspects- for example duration of time sleeping or number of arousals. However, there are also more subjective aspects to sleep too, such as restfulness. 

### Overall guidance and next steps

Some of the topics may be sensitive for people, and therefore it is important to not be overly direct and also to be ethical in the way you ask questions. If you are asking about mental health, for example, don't ask your participants about their own mental health. Remember that you will be working with your peers, and they will be known to you. Instead, ask about their opinions to do with mental health. 

When designing questions, you can refer to chapter 3 as cited in Braun and Clarke (Braun & Clarke, 2013), as well as guidance cited in Agee (2009). In terms of next steps, you need to agree on a topic area, and potential research questions. Complete your summative assignment for the Group Proposal (Research Question and Rationale) by the due date. 

### References (sorted by topic)

#### Topic 1: Green Spaces

#### Topic 2: Campus Climate

Advance HE (n.d. -a). Lesbian, gay and bisexual people. Advanced HE. Retrieved January 10, 2022, from https://www.advance-he.ac.uk/guidance/equality-diversity-and-inclusion/creating-inclusive-environment/lesbian-gay-and- bisexual-people#Work  

Advance HE (n.d. -b). Tackling racism on campus: Raising awareness and creating the conditions for confident conversations. Advanced HE. Retrieved January 10, 2022, from https://www.advance-he.ac.uk/tackling-racism-campus#resources 

Bilimoria, D., & Stewart, A. J. (2009). "don't ask, don't tell": The academic climate for lesbian, gay, bisexual, and transgender faculty in science and engineering. NWSA Journal, 21(2), 85-103. 

Bunce, L., King, N., Saran, S., & Talib, N. (2019). Experiences of black and minority ethnic (BME) students in higher education: Applying self-determination theory to understand the BME attain- ment gap. Studies in Higher Education, 46(3), 1–14. https://doi.org/10.1080/03075079.2019. 1643305 

Cech, E. A., & Waidzunas, T. J. (2021). Systemic inequalities for LGBTQ professionals in STEM. Science Advances, 7(3)https://doi.org/10.1126/ sciadv.abe0933 

Darney, M., Chang, C. Y., McCullough, R., Huffstead, M., & Smith, J. (2019). A phenomenological study of the experiences of master’s-level students of color in counsellingprograms. Teaching and Supervision in Counseling, 1(2), 31–45. https:// doi.org/10.7290/tsc010203 

De Oliveira, B. (2020, September). We must act to decolonise psychology. The Psychologist, 33, 4. https://thepsychologist.bps.org.uk/volume-33/ september-2020/standing-against-racism 

Forbes, T. D. (2020). Queer-free majors?: LGBTQ + college students’ accounts of chilly and warm academic disciplines. Journal of LGBT Youth, , 1-20. https:// doi.org/10.1080/19361653.2020.1813673 

Gillborn, Woolnough, Jankowski & Sandle (2021): “Intensely white”: psychology curricula and the (re)production of racism, Educational Review, DOI: 10.1080/00131911.2021.1978402 

Hart, J., & Fellabaum, J. (2008). Analyzing campus climate studies: Seeking to define and understand. Journal of Diversity in Higher Education, 1(4), 222-234. https:// doi.org/10.1037/a0013627 

Johnson, A., & Joseph-Salisbury, R. (2018). ‘Are you supposed to be in here?’ Racial microaggressions and knowledge production in higher education. In J. Arday & H. S. Mirza(Eds.), Dismantling race in higher education (pp. 143–160). Palgrave Macmillan. 

Patridge, E.V., Barthelemy, R. S., & Rankin, S. R. (2014) Factors impacting the academic climate for LGBQ STEM faculty. J. Women Minorities Sci. Eng. 20, 75–98 DOI: 10.1615/JWomenMinorScienEng.2014007429 

Rankin, S., Garvey, J. C., & Duran, A. (2019). A retrospective of LGBT issues on US college campuses: 1990–2020. International Sociology, 34(4), 435-454. https:// doi.org/10.1177/0268580919851429 

UCAS (2021a). Next Steps: What is the experience of LGBT+ students in education? https://www.ucas.com/next-steps-what-experience-lgbt-students-education? hash=iWMsuoMpHoBhyvsmDKLbZWe3Rl3MaR8LRUIQUMO_V28 

UCAS (2021b). UCAS undergraduate sector-level end of cycle data resources 2020. https://www.ucas.com/data-and-analysis/undergraduate-statistics-and-reports/ ucas-undergraduate-sector-level-end-cycle-data-resources-2020 

Universities UK (2019). Black, Asian and Minority Ethnic student attainment at UK universities: #CLOSINGTHEGAP. https://www.universitiesuk.ac.uk/sites/default/files/ field/downloads/2021-07/bame-student-attainment.pdf 

University of Glasgow,(n.d. -a). Information for LGBT+ students. University of Glasgow. Retrieved January 10, 2022, from https://www.gla.ac.uk/myglasgow/ humanresources/equalitydiversity/students/lgbt/ 

University of Glasgow,(n.d. -b). LGBT+ related information for staff. University of Glasgow. Retrieved January 10, 2022, from https://www.gla.ac.uk/myglasgow/ humanresources/equalitydiversity/staff/lgbt/ 

University of Glasgow,(n.d. -c). Understanding racism, transforming university cultures. University of Glasgow. Retrieved January 10, 2022, from https:// www.gla.ac.uk/myglasgow/humanresources/equalitydiversity/ understandingracism/#actionplansummary,summaryofreportfindings 

#### Topic 3: Students and mental health

Buchan, L. January, 2018. Students wait up to four months for mental health support at UK universities. The Independent. Retrieved from: https://www.independent.co.uk/news/uk/politics/students-mental-health-support-waitingtimes-counselling-university-care-diagnosis-treatment-liberal-a8124111.html  

Cooke, R., Bewick, B. M., Barkham, M., Bradley, M., & Audin, K. (2006). Measuring, monitoring and managing the psychological well-being of first year university students. British Journal of  Guidance & Counselling, 34(4), 505-517. doi:10.1080/03069880600942624 

Eisenberg, D., Golberstein, E., & Gollust, S. E. (2007). Help-seeking and access to mental health care in a university student population. Medical care, 594-601.

Gulliver, A., Griffiths, K. M., & Christensen, H. (2010). Perceived barriers and facilitators to mental health help-seeking in young people: a systematic review. BMC Psychiatry, 10(1), 113. 

Lu, S. H., Dear, B. F., Johnston, L., Wootton, B. M., & Titov, N. (2014). An internet survey of emotional health, treatment seeking and barriers to accessing mental health treatment among Chinese-speaking international students in Australia. Counselling Psychology Quarterly, 27(1), 96-108.  

Mowbray, C. T., Megivern, D., Mandiberg, J. M., Strauss, S., Stein, C. H., Collins, K., . . . Lett, R. (2006). Campus mental health services: recommendations for change. American Journal of Orthopsychiatry, 76(2), 226.  

Raunic, A., & Xenos, S. (2008). University counselling service utilisation by local and international students and user characteristics: A review. International Journal for the advancement of Counselling, 30(4), 262-267.  

Thomas, K. August, 2018. Mental health at university: know where to find support. The Guardian. Retrieved from: https://www.theguardian.com/education/2018/aug/14/mental-health-atuniversity-know-where-to-find-support 

Zivin, K., Eisenberg, D., Gollust, S. E., & Golberstein, E. (2009). Persistence of mental health problems and needs in a college student population. Journal of Affective Disorders, 117(3), 180-185.  


#### Topic 4: Belonging at University

Baumeister, R. F., & Leary, M. R. (1995). The need to belong: Desire for interpersonal attachments as a fundamental human motivation. Psychological Bulletin, 117(3), 497–529. https://doi.org/10.1037/0033-2909.117.3.497 

Blake, S., Capper, G., & Jackson, A. (2022, October). Building belonging in Higher Education. WONKHE, https://wonkhe.com/wp-content/wonkhe-uploads/2022/10/Building-Belonging-October-2022.pdf  

Cruwys, T., Haslam, S. A., Dingle, G. A., Haslam, C., & Jetten, J. (2014). Depression and social identity: An integrative review. Personality and Social Psychology Review, 18(3), 215-238. 

Freeman, T. M., Anderman, L. H., & Jensen, J. M. (2007). Sense of belonging in college freshmen at the classroom and campus levels. The Journal of Experimental Education, 75(3), 203-220. 

Greenaway, K. H., Haslam, S. A., & Bingley, W. (2018). Are “they” out to get me? A social identity model of paranoia. Group Processes & Intergroup Relations, 1368430218793190. 

Greenaway, K. H., Haslam, S. A., Cruwys, T., Branscombe, N. R., Ysseldyk, R., & Heldreth, C. (2015). From “we” to “me”: Group identification enhances perceived personal control with consequences for health and well-being. Journal of Personality and Social Psychology, 109(1), 53. 

Haslam, C., Haslam, S. A., Jetten, J., Bevins, A., Ravenscroft, S., & Tonks, J. (2010). The social treatment: The benefits of group interventions in residential care settings. Psychology and aging, 25(1), 157. 

Haslam, S. A., McMahon, C., Cruwys, T., Haslam, C., Jetten, J., & Steffens, N. K. (2018). Social cure, what social cure? The propensity to underestimate the importance of social factors for health.Social Science & Medicine, 198, 14-21. 

Levine, M., Prosser, A., Evans, D., & Reicher, S. (2005). Identity and emergency intervention: How social group membership and inclusiveness of group boundaries shape helping behavior. Personality and social psychology bulletin, 31(4), 443-453. 

Pedler, M. L., Willis, R., & Nieuwoudt, J.E. (2022) A sense of belonging at university: student retention, motivation and enjoyment, Journal of Further and Higher Education, 46 (3), 397-408, DOI: 10.1080/0309877X.2021.1955844 

Pittman, L. D., & Richmond, A. (2007). Academic and psychological functioning in late adolescence: The importance of school belonging. The Journal of Experimental Education, 75(4), 270-290. 

Samura, M. (2022, May 6) 3 ways to make ‘belonging’ more than a buzzword in higher ed. The Conversation, https://theconversation.com/3-ways-to-make-belonging-more-than-a-buzzword-in-higher-ed-175731  

Sani, F., Herrera, M., & Bowe, M. (2009). Perceived collective continuity and ingroup identification as defence against death awareness. Journal of Experimental Social Psychology, 45(1), 242-245. 

Sani, F., Herrera, M., Wakefield, J. R., Boroch, O., & Gulyas, C. (2012). Comparing social contact and group identification as predictors of mental health. British Journal of Social Psychology, 51(4), 781-790. 

Sani, F., Wakefield, J. R., Herrera, M., & Zeybek, A. (2017). On the association between greater family identification and lower paranoid ideation among non-clinical individuals: Evidence from cypriot and spanish students. Journal of Social and Clinical Psychology, 36(5), 396-418. 

Swartzman, S., Sani, F., & Munro, A. J. (2017). The role of social support, family identification, and family constraints in predicting posttraumatic stress after cancer. Psycho‐oncology, 26(9), 1330-1335. 

Wakefield, J. R., Bickley, S., & Sani, F. (2013). The effects of identification with a support group on the mental health of people with multiple sclerosis. Journal of Psychosomatic Research, 74(5), 420-426. 

Wilson, D., Jones, D., Bocell, F., Crawford, J., Kim, M. J., Veilleux, N., ... & Plett, M. (2015). Belonging and academic engagement among undergraduate STEM students: A multi-institutional study. Research in Higher Education, 56(7), 750-776. 

#### General

Agee, J. (2009). Developing qualitative research questions: a reflective process. International Journal of Qualitative Studies in Education, 22(4), 431-447.  

Braun, V., & Clarke, V. (2013). Successful qualitative research: A practical guide for beginners: sage. 

Marshall, C., & Rossman, G. B. (2014). Designing qualitative research: Sage publications. 

Rossi, P. H., Lipsey, M. W., & Freeman, H. E. (2003). Evaluation: A systematic approach: Sage publications. 

Silverman, D. (2015). Interpreting qualitative data: Sage. 